name: Upload YouTube Shorts

on:
  workflow_dispatch:        # ✅ เพิ่ม trigger สำหรับกดรันเอง
  schedule:
    # จันทร์ถึงพฤหัส + อาทิตย์ (3 ครั้ง)
    # เวลาไทย: 10:00, 15:00, 20:00
    # เวลา UTC: 03:00, 08:00, 13:00
    - cron: '0 3 * * 0,1,2,3,4'
    - cron: '0 8 * * 0,1,2,3,4'
    - cron: '0 13 * * 0,1,2,3,4'

    # ศุกร์–เสาร์ (4 ครั้ง)
    # เวลาไทย: 10:00, 13:00, 17:00, 20:00
    # เวลา UTC: 03:00, 06:00, 10:00, 13:00
    - cron: '0 3 * * 5,6'
    - cron: '0 6 * * 5,6'
    - cron: '0 10 * * 5,6'
    - cron: '0 13 * * 5,6'

jobs:
  upload_shorts:
    runs-on: ubuntu-latest

    env:
      SHEET_API_URL: ${{ secrets.SHEET_API_URL }}
      YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      YT_REDIRECT_URI: ${{ secrets.YT_REDIRECT_URI }}
      YT_ACCESS_TOKEN: ${{ secrets.YT_ACCESS_TOKEN }}
      YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node upload.js
